services:
  nginx:
    build: ./nginx
    image: nginxproxy
    container_name: nginxproxy
    networks:
      - default
    ports:
      - "9000:80"

  webserver:
    build: ./webserver
    image: webserver
    container_name: webserver
    networks:
      - default
